bundler_args: "--jobs 4 --retry 3"
cache: bundler
language: ruby
sudo: false
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head

gemfile:
  - gemfiles/rails-4-2.gemfile
  - gemfiles/rails-5-0.gemfile
  - gemfiles/rails-5-1.gemfile
  - gemfiles/rails-master.gemfile

matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/rails-5-0.gemfile
      rvm: 2.1
    - gemfile: gemfiles/rails-5-1.gemfile
      rvm: 2.1
    - gemfile: gemfiles/rails-master.gemfile
      rvm: 2.1
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails-master.gemfile

